# Generated by Django 5.0.6 on 2024-05-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("qb_points", models.FloatField()),
                ("wr_points_total", models.FloatField()),
                ("rb_points_total", models.FloatField()),
                ("te_points_total", models.FloatField()),
                ("k_points", models.FloatField()),
                ("def_points", models.FloatField()),
                ("total_points", models.FloatField()),
                ("expected_total", models.FloatField()),
                ("difference", models.FloatField()),
                ("points_against", models.FloatField()),
                ("projected_wins", models.IntegerField()),
                ("actual_wins", models.IntegerField()),
                ("wins_diff", models.IntegerField()),
            ],
        ),
    ]
