# Generated by Django 5.0.6 on 2024-05-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamperformance",
            name="actual_wins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="projected_wins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="wins_diff",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
