# Generated by Django 5.0.6 on 2024-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0003_teamperformance_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamperformance",
            name="opponent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="teamperformance",
            name="week",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
