# Generated by Django 5.0.6 on 2024-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0004_teamperformance_opponent_teamperformance_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamperformance",
            name="team_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="teamperformance",
            name="week",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="teamperformance",
            unique_together={("team_name", "week")},
        ),
    ]
