# Generated by Django 5.0.6 on 2024-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy_data", "0005_alter_teamperformance_team_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamperformance",
            name="rb_points",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamperformance",
            name="te_points",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamperformance",
            name="wr_points",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
